### ISSUE TITLE
uniapp开发支持这个WeConsole吗

### ISSUE THREAD

**Issue by LTAND** [weimobGroup/WeConsole#4]

**Comment by imingyu** [comment]
如果你只打包到微信小程序平台应该是可以的，但是没试过，还不确定，周末有时间试下

**Comment by nEdAy** [comment]
关注uniapp的支持（仅部署到微信小程序）

**Comment by bugaio** [comment]
插眼

**Comment by bugaio** [comment]
看了下 uni的文档,  它 是支持 小程序 组件的, 所以按照 它[官网教程](https://uniapp.dcloud.io/tutorial/miniprogram-subject.html#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E6%94%AF%E6%8C%81) 实现 即可

先 将 weconsole 的 npm 包下载到本地，然后将其中的dist/full文件夹拷贝至项目目录中, 跟 pages 同级,  并更名 full文件夹为 wxcomponents
<img width="351" alt="Snipaste_2022-04-17_14-35-16" src="https://user-images.githubusercontent.com/23302175/163703603-84365953-f31b-4f02-a15e-ad200ddff214.png">
然后在 pages.json中 , 添加  `usingComponents `
<img width="739" alt="Snipaste_2022-04-17_14-36-39" src="https://user-images.githubusercontent.com/23302175/163703635-96a7c403-35da-4a6c-a45f-65e2580f2761.png">
然后就可以 在 index.vue中 使用 组件了

不要忘了  在`main.js`中  
`import './wxcomponents/init';`

它 默认是  开启调试模式后  才显示的,   按照 weconsole的 文档 来手动调用api来显示 即可

**Comment by bweib** [comment]
关注uniapp的支持（部署到多端小程序）

**Comment by imingyu** [comment]
uniapp 是可以运行的（目前仅支持打包目标为微信小程序的产物），只有把`weconsole/dist/full`目录复制到已经编译好的uniapp目录中，然后在app.js中引入`full/init.js`是可以用的。
![image](https://github.com/weimobGroup/WeConsole/assets/7113267/4a9d4360-7750-411a-be2b-db34d87896b7)

**Comment by bweib** [comment]
您好！您的邮件我已收到，我会尽快查看的，谢谢！
